<?php
/**
 * @file  slash_developer.module
 */

include_once('slash_developer.features.inc');

/**
 * Implements hook_menu().
 */
function slash_developer_menu() {
  $items = array();
  if (variable_get('slash_developer_page_enabled')) {
    $items['developer'] = array(
      'title' => 'Developer',
      'page callback' => 'slash_developer_home',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'slash_developer.pages.inc',
    );
  }
  $items['developer/catalog'] = array(
    'title' => 'Developer API Catalog',
    'page callback' => 'slash_developer_catalog',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'slash_developer.pages.inc',
  );
  $items['admin/config/digitalstrategy/slash_developer'] = array(
    'title' => 'Digital Goverment Strategy developer page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slash_developer_settings'),
    'access arguments' => array('configure slash developer'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'slash_developer.admin.inc',
  );
  return $items;
}

function slash_developer_permission() {
  return array(
    'configure_slash_developer' => array(
      'title' => t('Configure slash developer'),
      'description' => t('Configure settings for the digital strategy developer page.'),
    ),
  );
}