<?php
/**
 * @file  slash_developer.module
 */

include_once('slash_developer.features.inc');

/**
 * Implements hook_menu().
 */
function slash_developer_menu() {
  $items = array();
  $items['developer'] = array(
    'title' => 'Developer',
    'page callback' => 'slash_developer_home',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'slash_developer.pages.inc',
  );
  $items['developer/catalog'] = array(
    'title' => 'Developer API Catalog',
    'page callback' => 'slash_developer_catalog',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'slash_developer.pages.inc',
  );
  return $items;
}
